swagger: "2.0"
info:
  title:  TME牛方案2.0 API
  version: "1.0.0"
  description: |
    # 公共说明
    ## 签名

    ### RSA签名密钥(计费相关接口使用)
    1. 密钥生成,rsa_public_key.pem 交由TME保管,用于验证rsa签名,私钥由厂商自行保存
    ```
    openssl genrsa -out rsa_private_key.pem 1024
    openssl pkcs8 -topk8 -inform PEM -in rsa_private_key.pem -outform PEM -nocrypt -out private_key.pem
    openssl rsa -in rsa_private_key.pem -RSAPublicKey_out -out rsa_public_key.pem
    ```
    2. 请直接将公钥rsa_public_key.pem内文本通过邮件发送给TME，以尽量降低沟通调试成本
    3. 使用rsa1024+pkcs1v1.5+sha256对http body(json序列化后)进行签名操作
    4. 将计算出的签名使用base64编码，并放置在头部signature字段
    5. 需申请两份密钥,1份生产环境使用，1份测试环境使用，请妥善保管

    ### MD5签名密钥(普通接口使用)
    1. 产品成功注册后,由TME提供,即pkey
    2. 具体注册流程请联系商务

    ## 调试

    1. 如需辅助定位问题，请至少提供签名(rsa版本签名,需再行计算签名md5,字母小写)以及请求时间点(精确到小时)
    2. 如返回参数字段的字段类型与文档内申明不符，请及时沟通
    3. **如对参数填写存在疑问，可适当参考本文档右侧参数样例**

    ## http

    1. http状态码,可能因架构微调,将返回非200(如认证信息未获通过返回401,以方便接入层监控统计),**请务必保证能正常处理**

    ## 参数错误

    1. 接口规划了通用参数错误提示，用于检查常规参数错误，如缺失，类型错误等
    2. error_msg字段将返回上述错误提示,格式为 field:[错误字段],rule:[违背的规则]，多个字段使用|分隔
    3. 错误字段名和接口文档内的参数名可能不完全一致,但基本不妨碍做出判断
    4. 常见规则及其说明如下

    |rule|说明|
    |--|--|
    |required|必传参数|
    |exists|必传参数|
    |type|参数类型|
    |min|最小值或最小长度|
    |max|最大值或最大长度|
    |enum|枚举值|
    |pid|合法pid|
    |ip|合法ip|
    |api|有效的api path|
    |timestamp|时间戳错误，比较当前时间戳，前后24h内|
    |base64|base64编码|
    |datetime|时间格式错误,有效格式:2018-11-22 04:27:00|

    ## 错误码
    1.错误码设计原则:除需要提示用户的情况外,尽量减少错误码,程序性错误请查看error_msg

    2.api通用参数验证将对参数错误做详细提示详见error_msg部分,其中field字段为不合法的参数,rule字段为非法原因

    3.error_msg返回格式不固定,仅用于调试使用,请勿用于程序代码

    |错误码|说明|
    |--|--|
    |200000|未定义错误码|
    |200001|参数错误|
    |200002|系统繁忙,如幂等接口并发调用等，通常由于用户并发操作造成|
    |200003|认证信息过期或错误,请重新登录|
    |200004|设备未激活,请使用api激活|
    |200005|当前sp暂未支持此接口|
    |200006|系统错误,如内部调用超时等，由于服务内部异常导致|
    |200007|无权调用此接口，原因可参考error_msg|
    |200100|酷码已经过期|
    |200101|酷码活动还未开启|
    |200102|酷码已经被使用|
    |200103|酷码不存在|
    |200200|可直充剩余次数为0|
    |200300|二维码未扫码|
    |200301|二维码扫码未确认|
    |200302|二维码超时失效|
    |200303|二维码扫码失败(如q音扫码结果已经获取过,后续获取将返回失败)|
    |200401|验证码失效|
    |200402|验证码无效|

    ## 更新日志

    |日期|接口|说明|
    |--|--|-|
    |2020-01-09|收藏歌单内歌曲列表|新增歌单类型字段用以区分自建歌单或他人歌单|
    |2020-01-09|推荐歌单|支持分页，且分页参数必填|
    |2020-01-09|收藏歌单内歌曲列表|添加返回参数playlist_extra_id，用于取消收藏|
    |2020-01-09|收藏或取消收藏歌单|添加参数playlist_extra_id以取消收藏; 添加返回参数playlist_extra_id,用于取消收藏|
    |2020-01-09|免费电台列表 免费电台歌曲|移除|
    |2020-02-13|收藏歌单内歌曲列表,歌单内歌曲列表|添加playable_code,is_vip_song字段(比其它接口多一枚举值-1,代表未知)|
    |2020-02-13|playable_code| 未知原因不能播放由 -1 更换为 9, -1改为是否可播放未知,需查询|
    |2020-02-13|设备激活接口|签名计算由rsa调整为md5|
    |2020-03-26|榜单列表接口|移除banner_url字段|
    |2020-03-26|歌手列表接口|添加imgurl歌手头像字段|

host: thirdsso.kugou.com
schemes:
  - https
basePath: /v2
produces:
  - application/json
paths:
  $ref: index/all.yaml
  #$ref: index/vip.yaml
  #$ref: index/custom.yaml
  #$ref: index/release.yaml

